---
product:
  type: object
  properties:
    id:
      type: integer
      format: int64
      x-field-extra-annotation: '@com.baomidou.mybatisplus.annotation.TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)'
    productCategoryId:
      type: integer
      format: int64
    unitPrice:
      type: number
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time