---
productQuery:
  allOf:
    - "$ref": "../schemas.yml#/schemas/product"
    - type: object
      properties:
        createdAtFrom:
          type: string
          format: date-time
        createdAtTo:
          type: string
          format: date-time
        updatedAtFrom:
          type: string
          format: date-time
        updatedAtTo:
          type: string
          format: date-time