---
productCategory:
  type: object
  x-class-extra-annotation: "@com.baomidou.mybatisplus.annotation.TableName(\"`product_category`\")"
  properties:
    id:
      type: integer
      format: int64
      x-field-extra-annotation: '@com.baomidou.mybatisplus.annotation.TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)'
    categoryName:
      type: string
    taxRate:
      type: number
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time